title: Thé de Chine
remote_theme: oisiflorus/maquillage-danslajungle

defaults:
  - scope:
      path: ""
    values:
      layout: location
      description: "Thaïs et Stéphane explorent l'univers des thés de Chine et proposent des expériences originales pour découvrir l'authentique culture du thé"

collections:
  montpellier:
    output: true
  documentation:
    output: true

plugins:
  - jekyll-remote-theme
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-default-layout
  - jekyll-titles-from-headings
